spring:
  application:
    name: THERAPY-PROVIDER-SERVICE
  # profile:
  #   active: dev
  cloud:
    config:
      name: therapy-provider-service
      uri: http://configuration-server:8888
  config:      
   import: "optional:configserver:"

